# Generated by Django 4.1.1 on 2022-10-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.CharField(choices=[('FILE', 'FILE'), ('FOLDER', 'FOLDER')], editable=False, max_length=255)),
                ('url', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.item')),
            ],
            options={
                'verbose_name_plural': 'Storage',
            },
        ),
    ]
